### ISSUE TITLE
Some icons are not correctly vertically aligned until a shell restart

### ISSUE THREAD

**Issue by luisfpg** [phocean/TopIcons-plus#59] opened 2017-03-15 12:15 UTC
For example, happens with the icon for Google Hangouts (chrome extension).
See the attached screenshot. It is duplicated because I have 2 Google profiles.
In the screenshot: one of the icons is all the way to the top.
The other one is aligned ok.
If I restart the shell, or change some TopIcons Plus setting (such as spacing) they are aligned correctly.

![image](https://cloud.githubusercontent.com/assets/1183737/23948005/e488906a-095f-11e7-868f-c85ec316fd04.png)

**Comment by luisfpg** [comment] 2017-03-15 12:33
Ah, and sometimes the icon is cropped as well, such as in this screenshot (which happened a few minutes after the first one):
![image](https://cloud.githubusercontent.com/assets/1183737/23948589/77be1dbc-0962-11e7-97fe-d9c197bdd367.png)

**Comment by phocean** [comment] 2017-03-31 04:30
I see only the second Hangouts is wrong, is that always like this ?
Do other icons/app get wrong ?
From where did you install topicons ? Please make sure there is no occurence of topicons in /usr/share/gnome-shell/extensions and ~/.local/share/gnome-shell/extensions. Then, install the version from github.

**Comment by luisfpg** [comment] 2017-03-31 11:17
Yes, the hangouts icon is the only one I see misaligned.
Maybe icons for some other Chrome extensions would also be misaligned, but I don't have any.
It was installed from the extensions website.
Now I've totally wiped out, cloned the github repo and it is exactly the same.
Here's a screenshot with the latest git version:
![image](https://cloud.githubusercontent.com/assets/1183737/24548193/52731096-15ea-11e7-8069-d9bea05314be.png)

**Comment by phocean** [comment] 2017-03-31 12:07
Thank you, I will install chrome and this extension and try to figure out.

**Comment by anthonyveiga** [comment] 2017-04-05 12:26
I see the same issue with Pidgin's tray icon. Even a reload won't fix it, because at the first status change it goes back to this state.
![misaligned-topicons-plus](https://cloud.githubusercontent.com/assets/25016421/24705368/9067eea6-19d9-11e7-8644-f06485b7b70e.gif)

**Comment by daaelar** [comment] 2017-04-05 12:28
I see the same issue with Pidgin's tray icon. A reload only fixes it temporarily, as it reverts at the first status change (received message, disconnected, etc)
![misaligned-topicons-plus](https://cloud.githubusercontent.com/assets/4164712/24705407/c530c950-19d9-11e7-8759-11ba578d76f5.gif)

**Comment by phocean** [comment] 2017-04-17 10:32
@daaelar I am not sure it is the same issue and pidgin tray icon is known to be buggy. See #6.

**Comment by phocean** [comment] 2017-04-17 10:37
@luisfpg I cannot reproduce the issue. What are:

* you gnome-shell theme
* your icon theme

Can you also take a screenshot of the topicons settings?

Thanks.

**Comment by luisfpg** [comment] 2017-04-17 13:08
I'm using Arc Dark GTK / shell theme.
For icons, I'm using Paper. However, the Hangouts icon is not influenced by the system icon theme.
Here's a screenshot of the settings:
![image](https://cloud.githubusercontent.com/assets/1183737/25089716/b1df4af4-2355-11e7-8568-d70a2c1dda9d.png)

**Comment by glaubersm** [comment] 2017-09-02 11:37
I can confirm pamac package manager sometimes has cropped icon under Gnome Wayland session.
My topicons plus extension was installed via gnome shell extensons website.

**Comment by glaubersm** [comment] 2017-09-02 12:18
My screenshot shows cropped pamac icon

![pamac-topiconsplus](https://user-images.githubusercontent.com/15967631/29995440-bc1112ec-8fbf-11e7-9d5c-85fd3e089f45.png)

**Comment by nxadm** [comment] 2017-09-30 11:59
Because issue #57 is closed, I add the info here.
In my case, the same regular time of crashes happen (mostly after boot) when using dropbox. Dropbox is the only "iconized" application that is automatically started by my session.

Feel free to ping me if more info (logs, etc) or tests are needed.

**Comment by phocean** [comment] 2017-09-30 13:14
@nxadm Why? This issue is unrelated. You can comment and reopen #57.

**Comment by nxadm** [comment] 2017-09-30 13:15
Ok, my excuses.

**Comment by anupam207** [comment] 2017-10-02 16:38
I'm having the same issue
### Before restarting shell
![before](https://user-images.githubusercontent.com/20688749/31088069-f89a4b42-a7bc-11e7-8f31-7cf5b54c1143.png)
(_l-to-r:_ GNOME Encfs Manager, uGet, Thunderbird via Firetray, alarm-clock-applet)
### After restarting shell
![after](https://user-images.githubusercontent.com/20688749/31088068-f890dd96-a7bc-11e7-9579-36f912e32d6c.png)

Extension config:
![topicons-plus](https://user-images.githubusercontent.com/20688749/31088336-e7503ad0-a7bd-11e7-8673-777715ccec08.png)

Shell & GTK theme: Arc, Icon theme: Papirus
Distro: Ubuntu GNOME 17.04, shell version 3.24.2

**Comment by phocean** [comment] 2020-04-18 08:24
I think this issue has been fixed with recent merge requests.

Closing it, feel free to re-open if necessary.

**Closed as completed by phocean** 2020-04-18 08:24 UTC
Labels: bug, can't reproduce
