### ISSUE TITLE
Google chrome issue

### ISSUE THREAD

**Issue by miguelcarax** [phocean/TopIcons-plus#33] opened 2016-08-25 21:29 UTC
Sometimes I open google-chrome the extesion looks bad i have to restart it to get it to works again
(Icon should be between music icon and [1] workspace).
![captura de pantalla de 2016-08-25 23-27-50](https://cloud.githubusercontent.com/assets/9194709/17986575/a9556a50-6b1b-11e6-868d-326f80878835.png)

**Comment by phocean** [comment] 2016-08-26 01:29
I used to see this issue in old versions. Did you install the latest version from here or gnome extension site?
What is your system?
Do you mean you have this issue only with Chrome applications (which I think it is the only way to get the icon in the tray)?

**Comment by miguelcarax** [comment] 2016-08-26 09:13
I have ArchLinux with Gnome 3.20, I installed it from the [AUR package](https://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwidp-393d7OAhUJ1RoKHUuKDRYQFggeMAA&url=https%3A%2F%2Faur.archlinux.org%2Fpackages%2Fgnome-shell-extension-topicons-plus-git%2F&usg=AFQjCNG--0elwijPn87yn_m_VOP4DL02KA&sig2=CeC1vSlLSZejrOl8FUKKiw) . I think it's not chrome but any program that have a tray icon (it happens with telegram too). Anyways if i close chrome or telegram and reopen it it works again.

**Comment by phocean** [comment] 2016-08-26 16:18
Hmm i am not an Arc user, but the package is full of confusing links between the old extension and mine (with an outdated link).
So it is not clear to me at what version they are.
Please uninstall it, install it from my github repo (git clone or get v15 relase : https://github.com/phocean/TopIcons-plus/releases).
I bet you won't have such an issue anymore. If so, you should report the bug there, stressing them to clean up links and base it on tagged releases.
Thank you for letting me know the results.

**Comment by miguelcarax** [comment] 2016-08-26 16:33
Well, i just do that aaand still have the bug ;(

![captura de pantalla de 2016-08-26 18-32-52](https://cloud.githubusercontent.com/assets/9194709/18012854/8f9a00ee-6bbb-11e6-920f-d97cd20c37c9.png)

**Comment by phocean** [comment] 2016-08-26 16:42
With default gnome-shell theme?
Also, I need gnome-shell logs.

**Comment by miguelcarax** [comment] 2016-08-26 16:55
Also with default theme yes.

Output of `journalctl | grep -i topicons`

``` bash
ago 15 01:44:41 MiguelThinkPad gnome-tweak-tool.desktop[24709]: Gjs-Message: JS LOG: Extension topIcons@kevinboxhoorn.yahoo.com already installed in /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com. /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com will not be loaded
ago 15 01:44:48 MiguelThinkPad gnome-tweak-tool.desktop[24709]: Gjs-Message: JS LOG: Extension topIcons@kevinboxhoorn.yahoo.com already installed in /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com. /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com will not be loaded
ago 15 01:53:27 MiguelThinkPad gnome-tweak-tool.desktop[25708]: Gjs-Message: JS LOG: Extension topIcons@kevinboxhoorn.yahoo.com already installed in /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com. /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com will not be loaded
ago 16 12:22:20 MiguelThinkPad org.gnome.Shell.desktop[714]: onTrayIconRemoved@/home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com/extension.js:163
ago 16 12:22:20 MiguelThinkPad org.gnome.Shell.desktop[714]: onTrayIconRemoved@/home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com/extension.js:163
ago 16 20:13:35 MiguelThinkPad org.gnome.Shell.desktop[744]: onTrayIconRemoved@/home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com/extension.js:163
ago 26 11:10:13 MiguelThinkPad sudo[3558]:   miguel : a password is required ; TTY=pts/0 ; PWD=/tmp/yaourt-tmp-miguel/aur-gnome-shell-extension-topicons-plus-git ; USER=root ; COMMAND=list /usr/bin/pacman --color auto -U --noconfirm /tmp/yaourt-tmp-miguel/PKGDEST.guk/gnome-shell-extension-topicons-plus-git-r70.1c158ee-2-any.pkg.tar
ago 26 11:10:18 MiguelThinkPad sudo[3560]:   miguel : TTY=pts/0 ; PWD=/tmp/yaourt-tmp-miguel/aur-gnome-shell-extension-topicons-plus-git ; USER=root ; COMMAND=validate
ago 26 11:10:18 MiguelThinkPad sudo[3561]:   miguel : TTY=pts/0 ; PWD=/tmp/yaourt-tmp-miguel/aur-gnome-shell-extension-topicons-plus-git ; USER=root ; COMMAND=list /usr/bin/pacman --color auto -U --noconfirm /tmp/yaourt-tmp-miguel/PKGDEST.guk/gnome-shell-extension-topicons-plus-git-r70.1c158ee-2-any.pkg.tar
ago 26 11:10:18 MiguelThinkPad sudo[3562]:   miguel : TTY=pts/0 ; PWD=/tmp/yaourt-tmp-miguel/aur-gnome-shell-extension-topicons-plus-git ; USER=root ; COMMAND=/usr/bin/pacman --color auto -U --noconfirm /tmp/yaourt-tmp-miguel/PKGDEST.guk/gnome-shell-extension-topicons-plus-git-r70.1c158ee-2-any.pkg.tar
ago 26 11:10:24 MiguelThinkPad org.gnome.Shell.desktop[1377]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:03:38 MiguelThinkPad org.gnome.Shell.desktop[1377]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:06:33 MiguelThinkPad org.gnome.Shell.desktop[1377]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:14:16 MiguelThinkPad plank.desktop[818]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:22:22 MiguelThinkPad plank.desktop[818]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:23:55 MiguelThinkPad plank.desktop[818]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 15:45:00 MiguelThinkPad org.gnome.Shell.desktop[1377]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 15:45:05 MiguelThinkPad org.gnome.Shell.desktop[7345]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 15:53:37 MiguelThinkPad org.gnome.Shell.desktop[7345]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 16:28:09 MiguelThinkPad org.gnome.Shell.desktop[7345]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 17:01:49 MiguelThinkPad org.gnome.Shell.desktop[741]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 17:08:15 MiguelThinkPad org.gnome.Shell.desktop[1401]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 17:08:48 MiguelThinkPad plank.desktop[834]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 18:23:06 MiguelThinkPad sudo[7679]:   miguel : TTY=pts/0 ; PWD=/usr/share/gnome-shell/extensions ; USER=root ; COMMAND=/usr/bin/rm -rf TopIcons@phocean.net
ago 26 18:23:39 MiguelThinkPad sudo[7780]:   miguel : TTY=pts/0 ; PWD=/usr/share/gnome-shell/extensions ; USER=root ; COMMAND=/usr/bin/git clone https://github.com/phocean/TopIcons-plus TopIcons-plus@phocean.net
ago 26 18:23:50 MiguelThinkPad org.gnome.Shell.desktop[1401]: (gnome-shell:1401): Gjs-WARNING **: JS ERROR: Could not load extension TopIcons-plus@phocean.net: Error: uuid "TopIcons@phocean.net" from metadata.json does not match directory name "TopIcons-plus@phocean.net"
ago 26 18:24:48 MiguelThinkPad sudo[8171]:   miguel : TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=/usr/bin/rm -rf /usr/share/gnome-shell/extensions/TopIcons-plus@phocean.net

```

**Comment by phocean** [comment] 2016-08-26 17:04
I don't know why your gnome-shell is so picky about the metadata:

`JS ERROR: Could not load extension TopIcons-plus@phocean.net: Error: uuid "TopIcons@phocean.net" from metadata.json does not match directory name "TopIcons-plus@phocean.net"`

Can you edit the line in metadata.json an test again. It should be:

`"uuid": "TopIcons-plus@phocean.net",`

Also, it reports a double install, both from package and from git. Please uninstall the package to avoid any confusion.

**Comment by miguelcarax** [comment] 2016-08-26 17:18
I uninstalled the package from AUR and edit metadata.json and now it not even loading it

```
ago 15 01:44:41 MiguelThinkPad gnome-tweak-tool.desktop[24709]: Gjs-Message: JS LOG: Extension topIcons@kevinboxhoorn.yahoo.com already installed in /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com. /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com will not be loaded
ago 15 01:44:48 MiguelThinkPad gnome-tweak-tool.desktop[24709]: Gjs-Message: JS LOG: Extension topIcons@kevinboxhoorn.yahoo.com already installed in /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com. /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com will not be loaded
ago 15 01:53:27 MiguelThinkPad gnome-tweak-tool.desktop[25708]: Gjs-Message: JS LOG: Extension topIcons@kevinboxhoorn.yahoo.com already installed in /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com. /home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com will not be loaded
ago 16 12:22:20 MiguelThinkPad org.gnome.Shell.desktop[714]: onTrayIconRemoved@/home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com/extension.js:163
ago 16 12:22:20 MiguelThinkPad org.gnome.Shell.desktop[714]: onTrayIconRemoved@/home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com/extension.js:163
ago 16 20:13:35 MiguelThinkPad org.gnome.Shell.desktop[744]: onTrayIconRemoved@/home/miguel/.local/share/gnome-shell/extensions/topIcons@kevinboxhoorn.yahoo.com/extension.js:163
ago 26 11:10:13 MiguelThinkPad sudo[3558]:   miguel : a password is required ; TTY=pts/0 ; PWD=/tmp/yaourt-tmp-miguel/aur-gnome-shell-extension-topicons-plus-git ; USER=root ; COMMAND=list /usr/bin/pacman --color auto -U --noconfirm /tmp/yaourt-tmp-miguel/PKGDEST.guk/gnome-shell-extension-topicons-plus-git-r70.1c158ee-2-any.pkg.tar
ago 26 11:10:18 MiguelThinkPad sudo[3560]:   miguel : TTY=pts/0 ; PWD=/tmp/yaourt-tmp-miguel/aur-gnome-shell-extension-topicons-plus-git ; USER=root ; COMMAND=validate
ago 26 11:10:18 MiguelThinkPad sudo[3561]:   miguel : TTY=pts/0 ; PWD=/tmp/yaourt-tmp-miguel/aur-gnome-shell-extension-topicons-plus-git ; USER=root ; COMMAND=list /usr/bin/pacman --color auto -U --noconfirm /tmp/yaourt-tmp-miguel/PKGDEST.guk/gnome-shell-extension-topicons-plus-git-r70.1c158ee-2-any.pkg.tar
ago 26 11:10:18 MiguelThinkPad sudo[3562]:   miguel : TTY=pts/0 ; PWD=/tmp/yaourt-tmp-miguel/aur-gnome-shell-extension-topicons-plus-git ; USER=root ; COMMAND=/usr/bin/pacman --color auto -U --noconfirm /tmp/yaourt-tmp-miguel/PKGDEST.guk/gnome-shell-extension-topicons-plus-git-r70.1c158ee-2-any.pkg.tar
ago 26 11:10:24 MiguelThinkPad org.gnome.Shell.desktop[1377]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:03:38 MiguelThinkPad org.gnome.Shell.desktop[1377]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:06:33 MiguelThinkPad org.gnome.Shell.desktop[1377]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:14:16 MiguelThinkPad plank.desktop[818]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:22:22 MiguelThinkPad plank.desktop[818]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 14:23:55 MiguelThinkPad plank.desktop[818]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 15:45:00 MiguelThinkPad org.gnome.Shell.desktop[1377]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 15:45:05 MiguelThinkPad org.gnome.Shell.desktop[7345]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 15:53:37 MiguelThinkPad org.gnome.Shell.desktop[7345]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 16:28:09 MiguelThinkPad org.gnome.Shell.desktop[7345]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 17:01:49 MiguelThinkPad org.gnome.Shell.desktop[741]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 17:08:15 MiguelThinkPad org.gnome.Shell.desktop[1401]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 17:08:48 MiguelThinkPad plank.desktop[834]: Gjs-Message: JS LOG: Extension TopIcons@phocean.net already installed in /home/miguel/.local/share/gnome-shell/extensions/TopIcons@phocean.net. /usr/share/gnome-shell/extensions/TopIcons@phocean.net will not be loaded
ago 26 18:23:06 MiguelThinkPad sudo[7679]:   miguel : TTY=pts/0 ; PWD=/usr/share/gnome-shell/extensions ; USER=root ; COMMAND=/usr/bin/rm -rf TopIcons@phocean.net
ago 26 18:23:39 MiguelThinkPad sudo[7780]:   miguel : TTY=pts/0 ; PWD=/usr/share/gnome-shell/extensions ; USER=root ; COMMAND=/usr/bin/git clone https://github.com/phocean/TopIcons-plus TopIcons-plus@phocean.net
ago 26 18:23:50 MiguelThinkPad org.gnome.Shell.desktop[1401]: (gnome-shell:1401): Gjs-WARNING **: JS ERROR: Could not load extension TopIcons-plus@phocean.net: Error: uuid "TopIcons@phocean.net" from metadata.json does not match directory name "TopIcons-plus@phocean.net"
ago 26 18:24:48 MiguelThinkPad sudo[8171]:   miguel : TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=/usr/bin/rm -rf /usr/share/gnome-shell/extensions/TopIcons-plus@phocean.net
ago 26 19:09:12 MiguelThinkPad sudo[3548]:   miguel : a password is required ; TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=list /usr/bin/pacman -Rd gnome-shell-extensiono-topicons-plug-git gnome-shell-extensiono-topicons
ago 26 19:09:15 MiguelThinkPad sudo[3551]:   miguel : TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=list /usr/bin/pacman -Rd gnome-shell-extensiono-topicons-plug-git gnome-shell-extensiono-topicons
ago 26 19:09:15 MiguelThinkPad sudo[3552]:   miguel : TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=/usr/bin/pacman -Rd gnome-shell-extensiono-topicons-plug-git gnome-shell-extensiono-topicons
ago 26 19:09:19 MiguelThinkPad sudo[3622]:   miguel : TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=list /usr/bin/pacman -Rd gnome-shell-extension-topicons-plug-git gnome-shell-extension-topicons
ago 26 19:09:19 MiguelThinkPad sudo[3623]:   miguel : TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=/usr/bin/pacman -Rd gnome-shell-extension-topicons-plug-git gnome-shell-extension-topicons
ago 26 19:09:30 MiguelThinkPad sudo[3693]:   miguel : TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=list /usr/bin/pacman -Rd gnome-shell-extension-topicons-plus-git gnome-shell-extension-topicons
ago 26 19:09:30 MiguelThinkPad sudo[3694]:   miguel : TTY=pts/0 ; PWD=/home/miguel ; USER=root ; COMMAND=/usr/bin/pacman -Rd gnome-shell-extension-topicons-plus-git gnome-shell-extension-topicons
ago 26 19:14:07 MiguelThinkPad org.gnome.Shell.desktop[736]: (gnome-shell:736): Gjs-WARNING **: JS ERROR: Could not load extension TopIcons@phocean.net: Error: uuid "TopIcons-plus@phocean.net" from metadata.json does not match directory name "TopIcons@phocean.net"
```

**Comment by phocean** [comment] 2016-08-26 17:23
It is a mess, now it is switched:
`Error: uuid "TopIcons-plus@phocean.net" from metadata.json does not match directory name "TopIcons@phocean.net"`

The folder name has to match with the uuid, so just rename the folder into TopIcons-plus@phocean.net.

I am not saying I am sure it is the solution, but at leat we have to make it happy and clean all these error messages.

So far, it is most probably a setup issue, not a bug.

**Comment by miguelcarax** [comment] 2016-08-26 17:34
Still the same, sorry ;( 
Anyways, if i open chrome just after start up it gets bugged but when I open telegram it's reload and gets fine.

**Comment by phocean** [comment] 2016-08-26 18:30
I think Telegram is just a web app, I don't know how you get this Chrome icon, etc., so I need more testing.
I can't promise to do it soon as I am busy, but  I will check.

**Comment by phocean** [comment] 2016-09-10 17:01
Just tried Telegram as well as many apps, and I can't reproduce your issue:

![capture d ecran de 2016-09-10 18-59-14](https://cloud.githubusercontent.com/assets/4280885/18412183/c10798ac-7788-11e6-9ff4-45ba8e93d60a.png)

Moreover, checking again your screenshots, even the legacy tray (Gnome) looks bad: icons are missing or strangely zoomed and cut.

As I don't have any other similar report, I think it is unnique to your environment, sorry.
Try the latest version, just in case.

**Comment by phocean** [comment] 2016-09-11 08:56
I am closing it for now. If you still have the issue, please come back with precise steps on how I can reproduce it (exact Chrome installation, application, how you get the icons, etc.).

I would then reopen the case.

Good luck.

**Closed as completed by phocean** 2016-09-11 08:56 UTC
Labels: bug, can't reproduce
