### ISSUE TITLE
Sometimes tray position changes after resuming from lock screen

### ISSUE THREAD

**Issue by laggarcia** [phocean/TopIcons-plus#44] opened 2016-12-13 11:10 UTC
Sometimes, when resuming from lock screen, tray position changes. I need to unload and reload the extension in order to get the tray back to the original position I configured.

It is interesting to notice that this issue is intermittent for me. But it happens at least 70% of the times. I am currently using GNOME 3.22.2 in Fedora 25, but I see this issue since I started using this extension back in Fedora 24.

**Comment by alex505** [comment] 2016-12-14 11:54
I second that. The same bug appears since Fedora 24 at least. It happens often(but not always) after unlocking the system. I just restart gnome-shell(Alt+F2->r) but it's just annoying to do this every time.

Edit: Looks like the issue is similar to this: https://github.com/phocean/TopIcons-plus/issues/13
So here's the debug info. I disabled all extensions/themes etc. except TopIcons, and this is what `journalctl -xn -f /usr/bin/gnome-shell` says when i lock/unlock the system:

`Dec 14 15:45:38 hostname gnome-shell[1598]: Allocating size to ShellEmbeddedWindow 0x564c1c23e600 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
`
also when i change the tray position number this appears in logs in multiple lines(unlike the previous one which appears only twice when i lock and then unlock):

`
Dec 14 15:54:03 hostname gnome-shell[1598]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
`

**Comment by phocean** [comment] 2016-12-14 13:10
Ok, thanks for the detailed info. I was not aware of this.
Can you please just confirm that it does not occur with the legacy tray (topicons disabled) ?

**Comment by phocean** [comment] 2016-12-14 13:16
I failed to reproduce the bug myself.
I get the first error message:
`gnome-shell[1598]: Allocating size to ShellEmbeddedWindow 0x564c1c23e600 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?`
But even when topicons is disabled, so it is not related.

I do not get the second error message and nothing indicates for usre that it is linked to the extension.

But I keep investigating. :-)

**Comment by alex505** [comment] 2016-12-14 13:20
Well, i just enabled couple of other extensions+custom theme+icons etc. and with topicons disabled this message doesn't appear in logs. But when i enable topicons the message appears again(twice after i lock/unlock). The second one still appears for me when i change the tray position number in extension's settings. The system is Fedora 25 workstation x64

**Comment by phocean** [comment] 2016-12-14 13:26
Did you install it from the gnome website or from here ?
I am on the dev branch, going to switch back to master to see.

**Comment by laggarcia** [comment] 2016-12-14 13:27
On 12/14/2016 11:26 AM, phocean wrote:
> Did you install it from the gnome website or from here ?

I installed it from extensions.gnome.org.

**Comment by alex505** [comment] 2016-12-14 13:30
Yes, from exnsions.gnome.org. Also i just noticed that the first message also appears when [system-monitor](https://extensions.gnome.org/extension/120/system-monitor/) extension is enabled. Disabling it leaves only topicons-related ones(of the same type i mean).

**Comment by phocean** [comment] 2016-12-14 13:30
Ok... #43 is also a strange issue, so I have to see if something is not messed up there.
I have no time to make more tests before this week-end, if you can, I would appreciate if you can test the dev branch from here.

**Comment by phocean** [comment] 2016-12-14 13:36
For the procedure:

```
git clone https://github.com/phocean/TopIcons-plus.git
git checkout dev
make install
```
Normally, it is enough to disable / re-enable the extension, but you might have to logout/login.

**Comment by alex505** [comment] 2016-12-14 18:23
Ok, so i tried this and the first message doesn't appear on dev branch anymore, the second one `(handler_id > 0)`  is still there though(but since it's not related to this bug and doesn't have any effect except flooding the logs i guess it's not critical)

Bad news is that the bug is still there. In order to reproduce it just install [system monitor](https://extensions.gnome.org/extension/120/system-monitor/) extension(may need to edit the `metadata.json` for the current gnome-shell version support) and set the tray position to the left of system-monitor applet (in my case it's '3'), then try to lock/unlock system couple times. Here's what happens
before lock
![before](https://cloud.githubusercontent.com/assets/22495001/21194152/efad7e0e-c23f-11e6-8612-be8bb517cf16.png)
after unlock
![after](https://cloud.githubusercontent.com/assets/22495001/21194176/051e088a-c240-11e6-80ee-807d1ae5bed5.png)
(notice the dropbox icon moved right)

One more thing - since the first message doesn't appear on the dev branch, there's nothing more related in logs. Anyways, i'll just post the whole log output with only topicons and system-monitor enabled, everything else(extensions, themes etc.) disabled/set to default:

```
Dec 14 21:06:43 hostname gnome-shell[8567]: GNOME Shell started at Wed Dec 14 2016 21:06:43 GMT+0300 (MSK)
Dec 14 21:06:50 hostname gnome-shell[8567]: Source ID 161 was not found when attempting to remove it
Dec 14 21:06:50 hostname gnome-shell[8567]: Source ID 287 was not found when attempting to remove it
Dec 14 21:06:50 hostname gnome-shell[8567]: JS LOG: System monitor applet disable
Dec 14 21:06:59 hostname gnome-shell[8567]: JS LOG: System monitor applet enabling
Dec 14 21:06:59 hostname gnome-shell[8567]: JS LOG: System monitor applet enabling done
Dec 14 21:07:05 hostname gnome-shell[8567]: Source ID 1001 was not found when attempting to remove it
Dec 14 21:07:05 hostname gnome-shell[8567]: Source ID 1015 was not found when attempting to remove it
Dec 14 21:07:05 hostname gnome-shell[8567]: JS LOG: System monitor applet disable
Dec 14 21:07:15 hostname gnome-shell[8567]: JS LOG: System monitor applet enabling
Dec 14 21:07:15 hostname gnome-shell[8567]: JS LOG: System monitor applet enabling done
```
Here ^ i locked/unlocked twice for the bug to appear(first 6 lines - after the first lock/unlock - no bug, the last 5 lines - after second immediate lock/unlock - bug happened). So i guess, there's nothing useful in logs :(

**Comment by phocean** [comment] 2016-12-14 18:47
Ok, very clear now. I totally misunderstood this issue at first, sorry for that.
Now I am not really surprised that it is buggy, as I remember this option is based on a dirty hack and it seems gnome-shell changes orders for some reason. 
At the time, I could not find a clean Gnome API to position the tray cleanly. I will check if it has changed as soon as I get time.
Please be patient, I am having hard times at work now :-)

**Comment by alex505** [comment] 2016-12-14 18:53
Hey, no worries ;-) I've been living with this bug for months, pretty sure i can wait some more, especially now when you're informed of it

**Comment by laggarcia** [comment] 2016-12-15 00:21
No hurry here as well. The extension is pretty useful and I am living with this issue for quite some time as well.

**Comment by phocean** [comment] 2016-12-18 12:00
Hi folks,

I made a lot of fixes on the dev branch, so you might want to have a look. A new release is coming soon.

BUT, regarding the tray position, I cannot come with a good solution.

By the way, a guy summarizes it well there: http://askubuntu.com/questions/453969/how-can-i-order-gnome3-shell-extensions-at-the-top

In short, except having a relative index, there is no better way to do (as far as I know). As stated, this index comes with no warranty: extensions may conflict (same index), system icons have priority, etc.

As it does not work as expected, I am thinking about removing this option and have it at index 0.

I am sorry but I don't want to have something that cannot work reliably, especially if this is a gnome-shell limitation.
Of course, if someone can help with a better solution, I would reimplement it.

On a related topic, I am adding a "center" position for those who want to have the icons by the clock.

**Comment by laggarcia** [comment] 2016-12-19 10:47
On 12/18/2016 10:00 AM, phocean wrote:
>
> Hi folks,
>
> I made a lot of fixes on the dev branch, so you might want to have a
> look. A new release is coming soon.
>
> BUT, regarding the tray position, I cannot come with a good solution.
>
> By the way, a guy summarizes it well there:
> http://askubuntu.com/questions/453969/how-can-i-order-gnome3-shell-extensions-at-the-top
>
> In short, except having a relative index, there is no better way to do
> (as far as I know). As stated, this index comes with no warranty:
> extensions may conflict (same index), system icons have priority, etc.
>
> As it does not work as expected, I am thinking about removing this
> option and have it at index 0.
>

This may be a good thing. It seems that other extensions I have just
stack into the left side of the bar in the order I activate them, and
they keep their position after screen unlock --- maybe I am just being
lucky. :) So, I am wondering if you don't try to set the position, if
they tray will remain where it is activated. Anyway, I agree with your
statement below that if this is not something gnome-shell can make work
correctly, you might not want to explore it for now.

> I am sorry but I don't want to have something that cannot work
> reliably, especially if this is a gnome-shell limitation.
> Of course, if someone can help with a better solution, I would
> reimplement it.
>
> On a related topic, I am adding a "center" position for those who want
> to have the icons by the clock.
>

**Comment by phocean** [comment] 2020-04-14 22:53
With the current way the API works, I don't see or know how to fix it.
Closing it for now.

**Closed as completed by phocean** 2020-04-14 22:53 UTC
Labels: enhancement, help wanted, wontfix
