### ISSUE TITLE
Update fails with errors

### ISSUE THREAD

**Issue by ros-financial-com** [phocean/TopIcons-plus#145] opened 2020-04-19 07:08 UTC
Hi there,

an error occurred when I tried to update the extension today.
Target system is a Fedora 31 Linux 5.5.15-200.fc31.x86_64 #1 SMP Thu Apr 2 19:16:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

`The installer provided this stacktrace:

The settings of extension TopIcons@phocean.net had an error:
```
Error: Schema org.gnome.shell.extensions.topicons could not be found for extension TopIcons@phocean.net. Please check your installation.
```

Stack trace:
```
getSettings@/home/ralf/.local/share/gnome-shell/extensions/TopIcons@phocean.net/convenience.js:88:15
_init@/home/ralf/.local/share/gnome-shell/extensions/TopIcons@phocean.net/prefs.js:28:26
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
buildPrefsWidget@/home/ralf/.local/share/gnome-shell/extensions/TopIcons@phocean.net/prefs.js:183:19
_showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:57:22
_extensionsLoaded@resource:///org/gnome/shell/extensionPrefs/main.js:320:13
_scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:298:13
asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:132:13
main@resource:///org/gnome/shell/extensionPrefs/main.js:707:5
@<main>:1:43
```
`

**Comment by Cyber-Oto** [comment] 2020-04-20 11:03
Duplicate of #144 

After today's update via https://extensions.gnome.org/extension/1031/topicons/ all works OK for me.

Keep up the good work!

**Comment by phocean** [comment] 2020-04-22 07:16
Thank you for the report. Yes, it was fixed :)

**Closed as completed by phocean** 2020-04-22 07:16 UTC
