### ISSUE TITLE
Some application icons (like Wire) need an extension refresh to appear

### ISSUE THREAD

**Issue by mohammadrafigh** [phocean/TopIcons-plus#42] opened 2016-11-28 10:45 UTC
the extension reserves space for some applications like Wire but wouldn't show the icon until I disable and enable the extension again. see the screenshots below.

![before refresh](https://s17.postimg.org/8wzee6cv3/1111.png)

![after refresh](https://s17.postimg.org/hqqav9ztr/22222.png)

also as you can see there is a problem with icon sizing too...

**Comment by DimaMklk** [comment] 2016-12-02 09:19
+1. Same problem with Slack

**Comment by phocean** [comment] 2016-12-10 17:04
Thanks for reporting. I just tried Wire and Slack with the dev branch and it works (I have increased the wait delay).
Can you check please?

![capture d ecran de 2016-12-10 18-03-05](https://cloud.githubusercontent.com/assets/4280885/21074833/fa81bed4-bf02-11e6-85b4-871b05edbefc.png)

**Comment by mohammadrafigh** [comment] 2016-12-12 11:53
thanks for replying,

still same issue in dev... it seems this issue happens in electron apps...

**Comment by phocean** [comment] 2016-12-12 13:25
I got the applications yesterday from the official sites, so they are probably the exact same electron apps.
As I cannot reproduce the issue, it is probably much trickier to debug than that.
I am also very much surprised with the icon size issue, as such patterns have been fixed months ago.

**Comment by phocean** [comment] 2016-12-12 13:28
Please give more info about your environment : gnome version, Linux distribution, exact Wire or whatever app version, output of `journalctl -f` output while unloading / loading the extension, etc.

**Comment by phocean** [comment] 2016-12-18 15:18
Hi, more technical info is needed, because I really cannot reproduce the bug.
I just pushed a lot of updates to the dev branch, can you have a look?

**Comment by mohammadrafigh** [comment] 2016-12-18 17:35
sorry for delay, some more info:

gnome version : 3.22.2
OS: Ubuntu 16.10
Wire version : 2.11.2685 (latest)

I will send journalctl output after trying your latest changes

**Comment by mohammadrafigh** [comment] 2016-12-18 17:43
ok for now I cannot reproduce the invisible icon issue but if happened again I will post a comment here. by the way about icon sizes may it be related to that I resized the top toolbar using a user-theme style like this?

```
#panel {
    font-size: 0.8em;
    height: 2.1em;
}
```

**Comment by phocean** [comment] 2016-12-18 19:16
I am not sure, so it is worth testing.

It could make sense as the extension bases the size on the theme scale factor. So your change might have some impact.

**Comment by phocean** [comment] 2016-12-18 20:19
Just leaving it here for future reference anyway: https://bugzilla.redhat.com/show_bug.cgi?id=1389875
Gnome is dropping support for status icons, so only pre Gtk+ 3.14 applications are going to work well on Wayland.

**Comment by mohammadrafigh** [comment] 2016-12-19 11:51
ok today I see the issue still persists... I found that when this happen... this issue happens only when Wire (or slack) has many data to sync so this takes some time to sync messages. also here is output of journalctl -f:

```
Dec 19 15:15:17 hp-pavilion-g6-notebook-pc gnome-tweak-tool.desktop[7352]: WARNING : Error loading desktopfile: /home/mohammad/.config/autostart/gnome-sound-applet.desktop
Dec 19 15:15:17 hp-pavilion-g6-notebook-pc gnome-tweak-tool.desktop[7352]: WARNING : Error loading desktopfile: /home/mohammad/.config/autostart/Temps.desktop
Dec 19 15:15:18 hp-pavilion-g6-notebook-pc dbus[1501]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
Dec 19 15:15:18 hp-pavilion-g6-notebook-pc systemd[1]: Starting Hostname Service...
Dec 19 15:15:18 hp-pavilion-g6-notebook-pc dbus[1501]: [system] Successfully activated service 'org.freedesktop.hostname1'
Dec 19 15:15:18 hp-pavilion-g6-notebook-pc systemd[1]: Started Hostname Service.
Dec 19 15:15:25 hp-pavilion-g6-notebook-pc gnome-shell[4454]: Attempting to remove actor of type 'StLabel' from group of class 'ShellGenericContainer', but the container is not the actor's parent.
Dec 19 15:15:26 hp-pavilion-g6-notebook-pc gnome-shell[4454]: Allocating size to ShellEmbeddedWindow 0x561672e28960 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Dec 19 15:15:26 hp-pavilion-g6-notebook-pc gnome-shell[4454]: Allocating size to ShellEmbeddedWindow 0x561672e28c20 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

```

**Comment by phocean** [comment] 2016-12-19 13:01
Thanks, the interesting line is this one:
`Dec 19 15:15:25 hp-pavilion-g6-notebook-pc gnome-shell[4454]: Attempting to remove actor of type 'StLabel' from group of class 'ShellGenericContainer', but the container is not the actor's parent.`

I will try to reproduce and fix it.

By the way, considering that Gnome support for legacy tray is dead (link above), I encourage you to:

- open a bug issue against Wire to ask them to change their design to align with Gnome (Apps should run in background and use the notification API, and Dash only),
- make voice to the Gnome user to tell them to consider their position.

 Us, users, should put some pressure so that change might happen.

I want to make clear that TopIcons is a hack relying on the Gtk/Gnome Shell capabilities. It cannot make miracles. If Gnome drops status icons so that it is messed up and breaks easily, there is nothing much an extension can do.

**Comment by mohammadrafigh** [comment] 2016-12-19 15:59
yes sure, thanks

**Comment by phocean** [comment] 2017-01-14 18:43
I am closing it, as I am little by little seeing that applications compiled with recent gtk versions break.
per bug https://bugzilla.redhat.com/show_bug.cgi?id=1389875, status icons are being removed from gtk, so there is no hope for a fix at the extension level.

Please, do comment and make voice on the Gnome project, otherwise we won't see anything change.

**Closed as completed by phocean** 2017-01-14 18:43 UTC
Labels: invalid
