### ISSUE TITLE
pidgin icon disappearing

### ISSUE THREAD

**Issue by freddyw** [phocean/TopIcons-plus#6] opened 2016-02-04 20:44 UTC
I love the extension, but I do have an issue with a disappearing pidgin icon (happened with the TopIcons by ag extension as well). Seems to be when flashing in case of a notification, but it is very intermittent. It appears as if an empty space is left behind. Clicking the empty space does bring the original screen forward, so the icon is not really gone, just not visible anymore. The only way to bring it back is either restarting pidgin, or disable/enable the extension.
I can not really tell whether this is a specific pidgin issue or if other programs with changing icons are also affected.

**Comment by phocean** [comment] 2016-02-04 22:09
I don't use Pidgin so it will take time before I am able to test and reproduce it.
One thing that I can say for now is that some other programs with changing icons, like Dropbox or Thunderbird (plugin), are not affected.

**Comment by freddyw** [comment] 2016-02-05 08:04
appreciate any effort you put in. What Thunderbird plugin are you referring to? Maybe I can test as well.

**Comment by phocean** [comment] 2016-02-05 08:27
It is called Firetray. Let me know if you have an issue with it too.

**Comment by freddyw** [comment] 2016-02-09 16:40
The issue seems to be directly related to the "Blink on new message" preference from pidgin. Once Disabled, the icon does not disappear. However, very hard to notice new messages then. Used  Fedora 21 with lxpanel (LXDE desktop) before, never used to be a problem there. The default legacy tray from gnome3 (it is called that way) works correctly as well, but is totally unworkable. Sure hope you can find anything.

**Comment by phocean** [comment] 2016-02-10 07:37
Ok, I will have a look on that next week-end. If Pigdin destroys  its parrent container, then this could be trouble due to the way the extension works.

-----Original Message-----

**Comment by phocean** [comment] 2016-02-10 17:48
I had a quick check and it actually works for a while, but get messed as soon there is a redraw in the bar (not solely the tray of topicons)  like when an extension is added or an icon added.
No error in Gnome-shell. I will investigate more later.

**Comment by phocean** [comment] 2016-02-13 21:47
Can't get the issue, especially with the actual level of Gnome documentation. Help needed.

**Comment by freddyw** [comment] 2016-02-14 10:46
Not sure what I can do to help, do not know the gnome environment well enough. I think your previous comment "or an icon added" pinpoints the issue. I guess the 'blinking' icon might actually be a new icon being added? Let's hope someone has the answer to this one.

**Comment by phocean** [comment] 2016-03-26 13:50
Just to leave a note here: I have used the legacy tray for a while, and in some occasion the disappearance issue also occurs there. Even though, less frequently.

**Comment by phocean** [comment] 2016-05-22 19:22
Hi, in case you are still using the extension, can you test the last version here?
In my environment the issue was fixed somehow while I fixed HDPI support.

**Comment by freddyw** [comment] 2016-05-22 20:23
Just installed the latest version, will let you know the results!

**Comment by freddyw** [comment] 2016-05-23 07:11
Unfortunately it does not seem to work. As soon as I enable "Blink on new message" the icon disappears upon new chats.

**Comment by phocean** [comment] 2016-05-24 15:06
Still working with mine, strange. Just leaving here a few pointers to the long history of issues with Pidgin notification:
https://github.com/linuxmint/Cinnamon/issues/3223
https://github.com/wincinderith/topicons/pull/4
https://developer.pidgin.im/ticket/11922

**Comment by phocean** [comment] 2016-06-19 15:36
I also became a Pidgin user and it (sometimes) happened on my environment, but either with or without the extension.
So there is an incompatibility somewhere between Pidgin and Gnome, but I bet that there is something wrong with Pidgin due to the bug history and the fact that other programs are not affected.

Anyway, a more elegant workaround is to:
- deactivate blinking on the status icon,
- use the pidgin IM extension : https://github.com/muffinmad/pidgin-im-gnome-shell-extension

It provides a better integration with Gnome, in my humble opinion.

Sorry for that, but I am closing it as "won't fix"...

**Closed as completed by phocean** 2016-06-19 15:36 UTC
Labels: bug, wontfix

**Comment by freddyw** [comment] 2016-06-19 18:14
I have deactivated blinking and am using the pidgin gnome extension. Was hoping there was a solution, but I agree that the problem appears to be a pidgin/gnome issue. Anyways, thanks a lot for trying!!

**Comment by zelch** [comment] 2017-03-07 02:08
Please try the attached pidgin patch with blinking enabled and see if it resolves your problem.

Note, this makes a couple of obvious UI changes to how blinking works.

The first, and more obvious, is that it now alternates between the alert icon and the non-alert icon, instead of between the alert icon and a blank icon.

The second, and less obvious, is that an alert takes priority of being in a connecting state, instead of the other way around.  I probably shouldn't lump this in, but I consider 'you have a new message' to be more important than 'you are connecting'.  And since you now see the other state half the time...

On a technical level, GTK no longer recommends the use of the API that pidgin is using to blink the icon, and they have removed it from newer versions of GTK.  It is thus less surprising than it could be that it doesn't work perfectly.  As such, we change the icon repeatedly instead of relying on GTK doing it for us.  This seems to work more reliably.

The old UI could be approximated by making some blank icon images in the different icon sizes, but I honestly can't be bothered right now.

[pidgin_tray_new_style_blink.txt](https://github.com/phocean/TopIcons-plus/files/823156/pidgin_tray_new_style_blink.txt)

**Comment by phocean** [comment] 2017-03-07 06:17
Congrats for the contribution, I will have to test it. Have you submitted it upstream ?
I hope it would do it in the main code.

**Comment by zelch** [comment] 2017-03-07 06:33
https://developer.pidgin.im/ticket/17174 is the upstream ticket.  I'm not sure how often they review those though, looking at the history.

**Comment by freddyw** [comment] 2017-03-15 08:46
Tried and tested it on 2.11 (just a few days) and compiled 2.12 with this patch this morning. So far so good, works as advertised!

**Comment by geckon** [comment] 2017-07-11 10:33
It seems the upstream ticket is still unnoticed though.
