### ISSUE TITLE
Startup applications are already running by the time the tray is initialized

### ISSUE THREAD

**Issue by ntrrgc** [phocean/TopIcons-plus#105] opened 2017-11-22 15:36 UTC
Some startup applications try to initialize their tray icons but fail to do that because the tray has not been initialized yet and show up their main window in order to not be completely window-less. Then TopIcon Plus initializes the tray, but it's too late.

I can reproduce this issue consistently with [copyq](https://github.com/hluk/CopyQ) (a clipboard manager) in gnome 3.26.2, Fedora 27.

**Comment by Th3Z0ne** [comment] 2017-11-24 19:33
Can confirm that for onwcloud client - under xorg its happening like that, running in wayland session it does work though.

**Comment by ashleybone** [comment] 2017-11-30 16:29
This is also an issue for keepassx and keepassxc, though I have noticed that if I set keepassxc to start "unminimized", the tray icon does appear.

**Comment by phocean** [comment] 2018-10-24 08:16
Can you confirm if the issue is still here?
Please `git pull` the lastest version.

There is a delay of 1 sec before bringing the tray up, so that may be causing your issues. Testing will be required to make sure that removing it does not break something else.

**Comment by phocean** [comment] 2020-04-14 23:07
No feedback, probably fixed. Closing it.

**Closed as completed by phocean** 2020-04-14 23:07 UTC
