### ISSUE TITLE
Crashing gnome-shell during login / screen unlock

### ISSUE THREAD

**Issue by arakan94** [phocean/TopIcons-plus#73] opened 2017-06-25 21:20 UTC
For few months, they're problems with gnome-shell crashes probably caused by TopIcons Plus..

See:
https://bugzilla.redhat.com/show_bug.cgi?id=1390198
https://bugzilla.redhat.com/show_bug.cgi?id=1433439

Could you please look into it? This extension is a must have on GNOME Shell!

**Comment by phocean** [comment] 2017-06-25 21:30
Please do not accuse Topicons-plus too quickly...

I see no evidence it is cause by a problem in TopIcons-plus. If it were so buggy, there would be more reports, including me using daily on Fedora and OpenSUSE.

Especially the first link shows a guy enabling both Topicons (old, unrelated, unsupported version) and Topicons-plus.
No wonder there are some issues, as it would be a race between two extensions doing the same thing.

So, I will investigate to see *if* it is related somehow to topicons-plus.

**Comment by arakan94** [comment] 2017-06-25 21:46
I understand.. It could be totally unrelated, but sometimes after those crashes, TopIcon Plus gets automatically disabled.. I've disabled TopIcons Plus for now (although it's pain to live without it - you made awesome extension) and so far, so good.. I'll see if it happens again (it happens quite regularly almost every day) and comment again..

Aside from that, is there any reasonable way to determine which (if any) extension caused crash? Can I turn some debug mode on?

Thanks for your time.. And I am sorry if it sounded accusative - I've said "probably" but English is not my primary language, so it probably came out wrong.. :)

**Comment by philfry** [comment] 2017-07-03 08:21
Hi, great extension, I love it, but unfortunately: same here. Gnome-shell segfaults every time I login / unlock the screensaver with TopIcons-plus enabled. When disabling this extension, no more segfaults happen. Sometimes I cannot even login at all, so I have to move the extension folder to somewhere else and move it back once I logged in.
The only other extensions I've enabled are the frippery extensions (in particular: bottom panel and move clock).

**Comment by phocean** [comment] 2017-07-03 08:27
Please provide more details : distribution, gnome version, backtrace, application enabled at session opening (with icon), etc.

**Comment by philfry** [comment] 2017-07-03 08:43
Fedora 25, Gnome-Shell 3.22.3, no apps with tray icons auto-started on login; pidgin running on screen lock/unlock.
Hardware is a Lenovo X1 Carbon 2nd with the Intel Haswell-ULT Integrated Graphics Controller on a **dual screen** setup.

`journalctl --user` shows
```
gnome-session[9595]: gnome-session-binary[9595]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
gnome-session-binary[9595]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
```

**Comment by phocean** [comment] 2017-07-03 09:55
The logs are not helpful. I forgot : gnome-shell +  gtk + icon themes ?

@arakan94 could you please give me the same info ?

I am trying to see what is in common and reproduce it in a test environment. Thanks !

**Comment by arakan94** [comment] 2017-07-05 08:29
I am on Fedora 25 as well with GNOME Shell 3.22.2 and also on dual screen setup. As GPU, I use AMD Radeon R9 270 - but that really shouldn't matter since it's completely abstracted for extensions.

At startup, I am running Evolution and Dropbox.

I've also disabled TopIcons Plus and haven't got gnome-shell crash since. But I've discovered another extension problem - sometimes, they simply won't load and I am getting messages such this:
`Attempting to add actor of type 'StBoxLayout' to a container of type 'StButton', but the actor has already a parent of type 'StButton'.`
`gsignal.c:2641: instance '0x559be0721400' has no handler with id '11904'`
`JS ERROR: Error: Type name Gjs_Settings is already registered`

It's also repeatedly trying to create Grid 0 and Grid 1 and ends up disabling even those extensions that, according to log, loaded just fine. Something is seriously wrong in current Fedora / GNOME :D

Anyway, I'll probably disable everything and try using TopIcons Plus exclusively to see if crashes happen and will provide backtrace if it happens.

**Comment by rusins** [comment] 2017-07-17 18:50
My shell has been crashing for months now, and I finally figured out that disabling topicons plus definitely stops it form crashing. Also seems as though the extension makes unlocking the screen take longer, and there is a noticeable flickering (specifically – the icons on the top bar pop in) when unlocking sometimes. Also Sometimes when a new app is launched its icon visibly appears on the bottom tray for such icons, although right clicking on an empty space on the topbar next to other tray icons makes its tray menu appear. (Likely separate bugs but the shell crashing is the most important one)

Using version 20 of the extension on Gnome 3.24.2.
OS: Arch Linux, everything up to date.
Happens both on Wayland and Xorg.
GTK theme: Adapta-Nokto-Eta, Icon theme: Numix circle, Shell theme: Adapta-Nokto
Possibly related note: I have the same laptop as @philfry 🤔

**Comment by semietiev** [comment] 2017-08-15 18:58
I had the same problem, but it seems to no longer occur when tray offset is changed from 1 to 2. At least when TopIcons Plus is aligned to right, I like it this way.

**Comment by phocean** [comment] 2017-08-20 09:05
I have mine most of time at offset 0. Thank you for the hint, I will test it for a while with offset 1.

**Comment by rusins** [comment] 2017-08-22 23:48
I enabled the extension with offset set to 1. Shell crashed in an hour's time (had been running without problems for days). Likely not the root cause of the problem.

**Comment by arakan94** [comment] 2017-08-23 06:40
I have been using it with offset 1 (default value?) and it keeps crashing (as a side note - I am also using Multi-monitor addon and 2 monitors). I will try it with offset 2.

**Comment by phocean** [comment] 2017-08-23 06:45
I had a gnome-shell crash recently when trying a different theme than stock one. Not having any issue with Adwaita.

I did not get any log, so not sure it is related to topicons though. Needs more testing, it is something to check.

As you can reproduce quite easily it seems, can you try with Adwaita as gnome-shell theme ? Or, better, disable "User Themes" extension ?

**Comment by arakan94** [comment] 2017-08-23 07:08
Disabling User Themes changed nothing for me. Offset 2 is also crashing. I've also tried disabling Multi-monitor addon and it still crashed very often.

After disabling TopIcon plus, I've logged in several times (both log out - log in and restart - log in) without problems.. I'll try to survive few days without your extension to see if crashing comes back or not..

**Comment by semietiev** [comment] 2017-08-23 11:35
I was wrong, it is not a settings fault. In my case, the crash is caused by Firefox notifications. I hadn't noticed this, because I changed my browser (to chromium) and TopIcons Plus settings at the same time and it was fine since then, so I assumed it was a tray offset fault. But after I returned to Firefox, crashes started to happen **sometimes** during notifications (as it was before), and only then.

Steps to reproduce would be turning on notifications for messenger.com (Facebook Messenger) and receive them. I am using Arch, and my Gnome theme is Adapta. I also have Noto Emoji installed, so I see emoji in the notifications.

**Comment by phocean** [comment] 2017-08-23 12:00
@semietiev thanks for the update. Then, do you think it is still related to topicons? Have you tried without topicons, and with topicons but stock gnome-shell theme ?

Don't you have any log in journalctl ?

Since this morning I have been running Topicons on top right and offset=2 without issue, so I think we can rule out this hypothesis.

**Comment by semietiev** [comment] 2017-08-23 13:22
@phocean well, topicons is the only thing that is crashing, so yes, I think it must be related. No problems if using another browser instead of Firefox or topicons is disabled. 

I will try to reproduce later with and without my other extensions (only shell themes and dash to dock) and gather jorunalctl logs, but i'm sure it will take some time.

I also want to thank you for your attitude. ;)

**Comment by phocean** [comment] 2017-08-23 13:30
@semietiev no problem ! This bug is a hell to track down. :-)

And it seems that you and @arakan94 have different issues. I may split it later.

Can you trigger the bug with this test notifications:

http://www.bennish.net/web-notifications.html

And, please, if you have any log, it would be super helpful.

**Comment by semietiev** [comment] 2017-08-23 14:55
I was unable to trigger the bug with notifications test that you provided, but when I was AFK it happened to me once again. Here is journalctl log between 15:30 and 16:30: https://pastebin.com/8VFzywpg (please notice my note on the top).

**Comment by Taz8du29** [comment] 2017-10-05 11:51
I have the same problem. Under the launchpad bug report, some users said it was related to your extension, and, yeah, disabling it solved for now the thing.

Here is a part of my syslog : 
```syslog
gnome-shell[1754]: Attempting to remove actor of type 'StBin' from group of class 'StBoxLayout', but the container is not the actor's parent.
gnome-shell[1754]: message repeated 2 times: [ Attempting to remove actor of type 'StBin' from group of class 'StBoxLayout', but the container is not the actor's parent.]
gnome-shell[1754]: ../../../../gobject/gsignal.c:2641: instance '0x561b7d57fc70' has no handler with id '72576'
gnome-shell[1754]: ../../../../gobject/gsignal.c:2641: instance '0x561b7d57fc70' has no handler with id '74611'
gnome-shell[1754]: ../../../../gobject/gsignal.c:2641: instance '0x561b7d57fc70' has no handler with id '74612'
gnome-shell[1754]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
gnome-shell[1754]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
gnome-shell[1754]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
```

I'm under Ubuntu 17.10 (artful) with gnome-shell 3.26.0, Arc-dark theme and adwaita icons theme.

Update : I'm trying to find which extension is causing problems, and it seems that users-themes conflicts with TI+.

**Comment by jafd** [comment] 2017-10-30 14:48
Disabling user themes did not stop from crashing on GNOME 3.26.1 on Fedora 27.

So I disabled TI+ just to see how it rolls.

It's always an "unlocking after a prolonged period of time" scenario that results in a crash.

**Comment by BernardoGO** [comment] 2017-11-10 16:09
I'm having the same problem.
Will try disabling topicons.

**Comment by ricardofunke** [comment] 2017-12-04 22:00
Same for me

Sometimes crashes when screen is locked. But the process of unlocking the screen is always slow and lagging when TopIcons is enabled.
[log.txt](https://github.com/phocean/TopIcons-plus/files/1528952/log.txt)

**Comment by stepri** [comment] 2017-12-06 22:06
I'm having the same issues.

**Comment by ogjerstad** [comment] 2018-01-04 14:52
I saw someone mention that aligning the icons to the left or right instead of in the middle also stopped it crashing. Seems promising for me, at least.

**Comment by Taz8du29** [comment] 2018-01-14 20:35
@ogjerstad I already have my items on the right side of the menu bar, and the problem still exists.

**Comment by ogjerstad** [comment] 2018-01-15 07:14
Yes, I have had multiple crashes as well now. Sorry for pointing in the wrong direction.

**Comment by phocean** [comment] 2020-04-28 08:02
I cannot reproduce it and I am closing it as this bug report is very old. Feel free to open a new issue if needed.

**Closed as completed by phocean** 2020-04-28 08:02 UTC
Labels: bug, can't reproduce
