### ISSUE TITLE
Status icons disappear when locking and unlocking the desktop

### ISSUE THREAD

**Issue by audreytoskin** [phocean/TopIcons-plus#126] opened 2019-06-20 16:20 UTC
(Hoping someone will take over this project...)

Vaguely similar to #44. Duplicate of #119, I think, but that was never resolved before closing. Possibly related to #72, but the original post there jumps right into the nitty-gritty details of the code, so I'm not sure...

1. Login to GNOME.
1. Launch an application that adds a status icon to the top bar.
1. Lock the screen (<kbd>Win</kbd>+<kbd>L</kbd>).
1. Login again to unlock.
1. Top bar status icons are gone.

Curiously, restarting GNOME Shell (<kbd>Alt</kbd>+<kbd>F2</kbd>, `r`, <kbd>Enter</kbd>) doesn't help, only closing and relaunching each application will make their status icons reappear. I've noticed this behavior with KeePassXC and Telegram, but I've seen at least one other user [report the same issue](https://bugzilla.redhat.com/show_bug.cgi?id=1721677) while using nagstamon.

Testing with TopIcons-Plus built from commit 76759a5, on Fedora 30 Workstation x86_64 with GNOME 3.32.2

**Comment by audreytoskin** [comment] 2019-06-20 16:29
Oh, and when I check in Looking Glass, it says "`TopIcons@phocean.net` has not emitted any errors."

**Comment by GabVenturato** [comment] 2019-06-30 15:03
I have the same problem (with Fedora 30, GNOME 3.32.2). I can confirm that also MEGA icon disappear.

**Comment by Doc73** [comment] 2019-09-17 17:58
Same issue with Gnome 3.30 and Debian Buster and Sid.

**Comment by phocean** [comment] 2020-04-14 23:33
Probably related to #100 .

**Comment by phocean** [comment] 2020-04-28 08:00
does anyone is still having the issue ? I cannot reproduce it at all...

Closing for now, reopen if necessary for newer investigations.

**Closed as completed by phocean** 2020-04-28 08:00 UTC
Labels: bug

**Comment by WBTMagnum** [comment] 2020-05-03 10:32
I can reproduce the behavior for the application Mumble on Ubuntu 18.04.4 running Gnome Shell 3.28.2 and TI+ V22. After locking/unlocking the desktop, the Mumble status icon is gone from the top bar.
